### ISSUE TITLE
--pipeto should optionally be piped per task

### ISSUE THREAD

**Issue by bjohas** [edtechhub/gtasks#20]
This happens in 'interactive' mode, but doesn't happen if 'interactive' is set to 'no'.

**Comment by bjohas** [comment]
Suggestion is to introduce something like
```
--interactive no_with_pipe_per_task = no
--interactive no_with_pipe_once 
```

**Comment by Resinderate** [comment]
I think I understand what you mean. So if I had 10 tasks and `--interactive no --pipe-to myscript.sh`, it would call `myscript.py` once with the 10 tasks as one blob of json. I want the option to still have `--interactive no` set but call `myscript.sh` 10 times, each time just getting the content of a single task. Right?

I would probably do it with a separate flag though, something like `--pipe-separately yes/no` which default so no (so that it defaults to the current behaviour), and would be ignored for `--interactive yes` which would always be separately.

Estimate: Less than 1 hour.

**Comment by bjohas** [comment]
Yes, `--pipe-separately yes/no` would work!

**Comment by Resinderate** [comment]
I've added PR #25 which implements this. It's done so that for each top level task it pipes it once, but I'm realising now that I never asked.. Do we ever want it to pipe all of the sub-tasks individually too? Or is the current approach sufficient?

If we want the sub-tasks to be piped separately too, perhaps we change the options to be `no/parents/children` or similar.

**Comment by bjohas** [comment]
No, this is sufficient! Thanks!
